### ISSUE TITLE
[Bug] Exception "Cause already initialized" browsing Mangadex & Manga Plus

### ISSUE THREAD

**Issue by QuentinLB** [az4521/TachiyomiAZ#108]
### Device information
* TachiyomiAZ version: v8.8.2-AZ
* Android version: 6.0.1
* Device: Lenovo TB 8703F

## Steps to reproduce
1. Browse new releases or open chapter from either mangadex or manga plus

### Expected behavior
I should see new releases or chapter

### Actual behavior
I get greeted with "Cause already initialized" background or snackbar

Open chapter full exception :

`
Thread: main
   	├ eu.kanade.tachiyomi.ui.reader.loader.ChapterLoader$loadChapter$4.invoke(ChapterLoader.kt:74)
   	└ eu.kanade.tachiyomi.ui.reader.loader.ChapterLoader$loadChapter$4.invoke(ChapterLoader.kt:72)
> Failed to fetch page list!
java.lang.IllegalStateException: Cause already initialized
   	at exh.util.ExceptionUtilKt.withRootCause(ExceptionUtil.kt:15)
   	at exh.util.ExceptionUtilKt.withRootCause(ExceptionUtil.kt:17)
   	at exh.util.ExceptionUtilKt.withRootCause(ExceptionUtil.kt:17)
   	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservableWithAsyncStacktrace$1$requestArbiter$1.request(OkHttpExtensions.kt:51)
   	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
   	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4$1.setProducer(OperatorOnErrorResumeNextViaFunction.java:130)
   	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
   	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
   	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservableWithAsyncStacktrace$lambda$0(OkHttpExtensions.kt:68)
   	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.$r8$lambda$CUa2Yatmbk1Li1z2c1T1LKJxmYQ(OkHttpExtensions.kt:0)
   	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(R8$$SyntheticClass:0)
   	at rx.Observable.unsafeSubscribe(Observable.java:10327)
   	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
   	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
   	at rx.Observable.unsafeSubscribe(Observable.java:10327)
   	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
   	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
   	at rx.Observable.unsafeSubscribe(Observable.java:10327)
   	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
   	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
   	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
   	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   	at rx.Observable.unsafeSubscribe(Observable.java:10327)
   	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
   	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
   	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   	at rx.Observable.unsafeSubscribe(Observable.java:10327)
   	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
   	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
   	at rx.Observable.unsafeSubscribe(Observable.java:10327)
   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
   	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
   	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
   	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
   	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
   	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
   	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
   	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
   	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   	at java.lang.Thread.run(Thread.java:818)
2024-11-11 13:16:55.134 18867-18867 X-LOG                   eu.kanade.tachiyomi.az               W  Thread: main
   	├ eu.kanade.tachiyomi.ui.reader.loader.ChapterLoader$loadChapter$4.invoke(ChapterLoader.kt:75)
   	└ eu.kanade.tachiyomi.ui.reader.loader.ChapterLoader$loadChapter$4.invoke(ChapterLoader.kt:72)
> (source.id: 2499283573021220255, source.name: MangaDex, manga.id: 338, manga.url: /manga/d4d43c50-ce1a-4751-b474-e239cf862f2a, chapter.id: 103876, chapter.url: /chapter/bee0e35a-de57-4959-ac24-1616cf644635)
`

Full zipped logcat export : [LENOVO-Lenovo-TB-8703F-Android-6.0.1_2024-11-11_132716.logcat.zip](https://github.com/user-attachments/files/17702525/LENOVO-Lenovo-TB-8703F-Android-6.0.1_2024-11-11_132716.logcat.zip)

### Other details
It doesn't happen with Webtoons.com (1.4.41) or ReadComicOnline (1.4.28)

Mangadex extension version : 1.4.194
Manga Plus extension version : 1.4.52

I thought it was a TLS issue because when I use Kotatsu (another manga reader app) I can open Mangadex but I see that you also use Conscrypt. 

Thanks for your help.

**Comment by az4521** [comment]
this *is* a TLS issue. older android devices (nougat (7) and below) are missing tons of different root certificates. here's the thing that's pinned in the discord channel for tachiaz in https://discord.gg/mihon

For users on older versions of Android (earlier than 7.1.1) seeing "Cause not initialized" or "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found" when trying to access MangaDex, you need to manually install a certificate on your device

Download the certificate from https://letsencrypt.org/certificates/ (Active → ISRG Root X1 → Self-signed → pem)
Install the certificate by following https://support.google.com/pixelphone/answer/2844832?hl=en (exact settings path may differ on your device)

**Comment by QuentinLB** [comment]
Worked great thank you !
